# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LockinThermometerUi2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(958, 410)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.sourceCombo = QtGui.QComboBox(Form)
        self.sourceCombo.setObjectName(_fromUtf8("sourceCombo"))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.sourceCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.sourceCombo)
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.sensorNameLe = QtGui.QLineEdit(Form)
        self.sensorNameLe.setObjectName(_fromUtf8("sensorNameLe"))
        self.horizontalLayout_5.addWidget(self.sensorNameLe)
        self.runPb = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runPb.sizePolicy().hasHeightForWidth())
        self.runPb.setSizePolicy(sizePolicy)
        self.runPb.setObjectName(_fromUtf8("runPb"))
        self.horizontalLayout_5.addWidget(self.runPb)
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.adrResistanceIndicator = EngineeringIndicator(Form)
        self.adrResistanceIndicator.setText(_fromUtf8(""))
        self.adrResistanceIndicator.setObjectName(_fromUtf8("adrResistanceIndicator"))
        self.horizontalLayout_5.addWidget(self.adrResistanceIndicator)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.attenuatorGroupBox = QtGui.QGroupBox(Form)
        self.attenuatorGroupBox.setObjectName(_fromUtf8("attenuatorGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.attenuatorGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.attenuatorGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.attenuatorGainSb = ScientificDoubleSpinBox(self.attenuatorGroupBox)
        self.attenuatorGainSb.setKeyboardTracking(False)
        self.attenuatorGainSb.setDecimals(8)
        self.attenuatorGainSb.setMinimum(1e-06)
        self.attenuatorGainSb.setMaximum(1000000.0)
        self.attenuatorGainSb.setSingleStep(1e-06)
        self.attenuatorGainSb.setProperty("value", 1.0)
        self.attenuatorGainSb.setObjectName(_fromUtf8("attenuatorGainSb"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.attenuatorGainSb)
        self.label_3 = QtGui.QLabel(self.attenuatorGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.attenuatorAttenuationSb = ScientificDoubleSpinBox(self.attenuatorGroupBox)
        self.attenuatorAttenuationSb.setKeyboardTracking(False)
        self.attenuatorAttenuationSb.setDecimals(8)
        self.attenuatorAttenuationSb.setMinimum(1e-06)
        self.attenuatorAttenuationSb.setMaximum(1000000.0)
        self.attenuatorAttenuationSb.setSingleStep(1e-06)
        self.attenuatorAttenuationSb.setProperty("value", 1.0)
        self.attenuatorAttenuationSb.setObjectName(_fromUtf8("attenuatorAttenuationSb"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.attenuatorAttenuationSb)
        self.label_2 = QtGui.QLabel(self.attenuatorGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sourceImpedanceSb = QtGui.QDoubleSpinBox(self.attenuatorGroupBox)
        self.sourceImpedanceSb.setKeyboardTracking(False)
        self.sourceImpedanceSb.setDecimals(3)
        self.sourceImpedanceSb.setMinimum(0.0)
        self.sourceImpedanceSb.setMaximum(1000000000.0)
        self.sourceImpedanceSb.setSingleStep(0.001)
        self.sourceImpedanceSb.setProperty("value", 1.0)
        self.sourceImpedanceSb.setObjectName(_fromUtf8("sourceImpedanceSb"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sourceImpedanceSb)
        self.horizontalLayout.addLayout(self.formLayout)
        self.horizontalLayout_6.addWidget(self.attenuatorGroupBox)
        self.seriesResistanceGroupBox = QtGui.QGroupBox(Form)
        self.seriesResistanceGroupBox.setObjectName(_fromUtf8("seriesResistanceGroupBox"))
        self.layoutWidget = QtGui.QWidget(self.seriesResistanceGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 24, 169, 190))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.driveResistanceSb = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.driveResistanceSb.setKeyboardTracking(False)
        self.driveResistanceSb.setDecimals(3)
        self.driveResistanceSb.setMinimum(0.0)
        self.driveResistanceSb.setMaximum(1000000000.0)
        self.driveResistanceSb.setSingleStep(0.0001)
        self.driveResistanceSb.setProperty("value", 1.0)
        self.driveResistanceSb.setObjectName(_fromUtf8("driveResistanceSb"))
        self.horizontalLayout_10.addWidget(self.driveResistanceSb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.leadResistanceSb = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.leadResistanceSb.setKeyboardTracking(False)
        self.leadResistanceSb.setDecimals(4)
        self.leadResistanceSb.setMinimum(0.001)
        self.leadResistanceSb.setMaximum(1000000000.0)
        self.leadResistanceSb.setSingleStep(0.001)
        self.leadResistanceSb.setProperty("value", 1.0)
        self.leadResistanceSb.setObjectName(_fromUtf8("leadResistanceSb"))
        self.horizontalLayout_9.addWidget(self.leadResistanceSb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_4.addWidget(self.label_20)
        self.calibrationCombo = QtGui.QComboBox(self.layoutWidget)
        self.calibrationCombo.setObjectName(_fromUtf8("calibrationCombo"))
        self.verticalLayout_4.addWidget(self.calibrationCombo)
        self.horizontalLayout_6.addWidget(self.seriesResistanceGroupBox)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.preampGroupBox = QtGui.QGroupBox(Form)
        self.preampGroupBox.setObjectName(_fromUtf8("preampGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.preampGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.preampGroupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.preampGainSb = QtGui.QDoubleSpinBox(self.preampGroupBox)
        self.preampGainSb.setKeyboardTracking(False)
        self.preampGainSb.setDecimals(6)
        self.preampGainSb.setMinimum(1e-05)
        self.preampGainSb.setMaximum(1000000.0)
        self.preampGainSb.setSingleStep(0.0001)
        self.preampGainSb.setProperty("value", 1.0)
        self.preampGainSb.setObjectName(_fromUtf8("preampGainSb"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.preampGainSb)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_3.addWidget(self.preampGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.visaCombo = VisaCombo(self.groupBox_2)
        self.visaCombo.setEnabled(True)
        self.visaCombo.setObjectName(_fromUtf8("visaCombo"))
        self.visaCombo.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.visaCombo)
        self.autoRangingCb = QtGui.QCheckBox(self.groupBox_2)
        self.autoRangingCb.setObjectName(_fromUtf8("autoRangingCb"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.autoRangingCb)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.minSensitivityCombo = EnumComboBox(self.groupBox_2)
        self.minSensitivityCombo.setObjectName(_fromUtf8("minSensitivityCombo"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.minSensitivityCombo)
        self.morePb = QtGui.QPushButton(self.groupBox_2)
        self.morePb.setObjectName(_fromUtf8("morePb"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.morePb)
        self.horizontalLayout_8.addLayout(self.formLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.adjustExcitationCb = QtGui.QCheckBox(self.groupBox)
        self.adjustExcitationCb.setObjectName(_fromUtf8("adjustExcitationCb"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.adjustExcitationCb)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sensorVoltageSb = QtGui.QDoubleSpinBox(self.groupBox)
        self.sensorVoltageSb.setKeyboardTracking(False)
        self.sensorVoltageSb.setDecimals(6)
        self.sensorVoltageSb.setSingleStep(1e-06)
        self.sensorVoltageSb.setProperty("value", 0.0001)
        self.sensorVoltageSb.setObjectName(_fromUtf8("sensorVoltageSb"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.sensorVoltageSb)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.sensorVoltageIndicator = EngineeringIndicator(self.groupBox)
        self.sensorVoltageIndicator.setText(_fromUtf8(""))
        self.sensorVoltageIndicator.setObjectName(_fromUtf8("sensorVoltageIndicator"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.sensorVoltageIndicator)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.sensorCurrentIndicator = EngineeringIndicator(self.groupBox)
        self.sensorCurrentIndicator.setText(_fromUtf8(""))
        self.sensorCurrentIndicator.setObjectName(_fromUtf8("sensorCurrentIndicator"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.sensorCurrentIndicator)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.sensorPowerIndicator = EngineeringIndicator(self.groupBox)
        self.sensorPowerIndicator.setText(_fromUtf8(""))
        self.sensorPowerIndicator.setObjectName(_fromUtf8("sensorPowerIndicator"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.sensorPowerIndicator)
        self.toleranceSb = QtGui.QSpinBox(self.groupBox)
        self.toleranceSb.setMaximum(100)
        self.toleranceSb.setProperty("value", 10)
        self.toleranceSb.setObjectName(_fromUtf8("toleranceSb"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.toleranceSb)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.updateLed = LedIndicator(self.groupBox)
        self.updateLed.setProperty("color", QtGui.QColor(0, 170, 0))
        self.updateLed.setObjectName(_fromUtf8("updateLed"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.updateLed)
        self.sensorIndicator = EngineeringIndicator(self.groupBox)
        self.sensorIndicator.setText(_fromUtf8(""))
        self.sensorIndicator.setObjectName(_fromUtf8("sensorIndicator"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.sensorIndicator)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_19)
        self.temperatureIndicator = TemperatureIndicator(self.groupBox)
        self.temperatureIndicator.setObjectName(_fromUtf8("temperatureIndicator"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.FieldRole, self.temperatureIndicator)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_21)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.plotYAxisCombo = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotYAxisCombo.sizePolicy().hasHeightForWidth())
        self.plotYAxisCombo.setSizePolicy(sizePolicy)
        self.plotYAxisCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.plotYAxisCombo.setObjectName(_fromUtf8("plotYAxisCombo"))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.plotYAxisCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.plotYAxisCombo)
        self.clearPb = QtGui.QPushButton(Form)
        self.clearPb.setObjectName(_fromUtf8("clearPb"))
        self.horizontalLayout_7.addWidget(self.clearPb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.configCombo = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configCombo.sizePolicy().hasHeightForWidth())
        self.configCombo.setSizePolicy(sizePolicy)
        self.configCombo.setMinimumSize(QtCore.QSize(60, 0))
        self.configCombo.setEditable(True)
        self.configCombo.setObjectName(_fromUtf8("configCombo"))
        self.horizontalLayout_7.addWidget(self.configCombo)
        self.loadPb = QtGui.QPushButton(Form)
        self.loadPb.setObjectName(_fromUtf8("loadPb"))
        self.horizontalLayout_7.addWidget(self.loadPb)
        self.savePb = QtGui.QPushButton(Form)
        self.savePb.setObjectName(_fromUtf8("savePb"))
        self.horizontalLayout_7.addWidget(self.savePb)
        self.deletePb = QtGui.QPushButton(Form)
        self.deletePb.setObjectName(_fromUtf8("deletePb"))
        self.horizontalLayout_7.addWidget(self.deletePb)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_8.setBuddy(self.sourceCombo)
        self.label.setBuddy(self.attenuatorGainSb)
        self.label_3.setBuddy(self.attenuatorAttenuationSb)
        self.label_2.setBuddy(self.sourceImpedanceSb)
        self.label_11.setBuddy(self.driveResistanceSb)
        self.label_12.setBuddy(self.leadResistanceSb)
        self.label_20.setBuddy(self.sensorIndicator)
        self.label_10.setBuddy(self.preampGainSb)
        self.label_7.setBuddy(self.visaCombo)
        self.label_4.setBuddy(self.sensorVoltageSb)
        self.label_5.setBuddy(self.sensorVoltageIndicator)
        self.label_6.setBuddy(self.sensorPowerIndicator)
        self.label_13.setBuddy(self.sensorIndicator)
        self.label_19.setBuddy(self.sensorIndicator)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_8.setText(_translate("Form", "Source", None))
        self.sourceCombo.setItemText(0, _translate("Form", "Voltage source", None))
        self.sourceCombo.setItemText(1, _translate("Form", " 50 mA FS", None))
        self.sourceCombo.setItemText(2, _translate("Form", "  5 mA FS", None))
        self.sourceCombo.setItemText(3, _translate("Form", "500 uA FS", None))
        self.sourceCombo.setItemText(4, _translate("Form", " 50 uA FS", None))
        self.sourceCombo.setItemText(5, _translate("Form", "  5 uA FS", None))
        self.sourceCombo.setItemText(6, _translate("Form", "500 nA FS", None))
        self.label_14.setText(_translate("Form", "Sensor name", None))
        self.runPb.setText(_translate("Form", "Start", None))
        self.label_16.setText(_translate("Form", "ADR", None))
        self.attenuatorGroupBox.setTitle(_translate("Form", "Attenuator", None))
        self.label.setText(_translate("Form", "Gain", None))
        self.label_3.setText(_translate("Form", "Attenuation", None))
        self.label_2.setText(_translate("Form", "Source impedance", None))
