# -*- coding: 'utf-8 -*-
"""
Created on Thu Nov 19 15:10:57 2015

@author: Felix Jaeckel <felix.jaeckel@wisc.edu>
"""

DeviceTypes = {
      1: 'Not a National Instruments DAQ device',
      7: 'PC-DIO-24',
      8: 'AT-DIO-32F',
     12: 'PC-DIO-96',
     13: 'PC-LPM-16',
     15: 'AT-AO-6',
     25: 'AT-MIO-16E-2',
     26: 'AT-AO-10',
     32: 'NEC-MIO-16E-4',
     35: 'DAQCard DIO-24',
     36: 'AT-MIO-16E-10',
     37: 'AT-MIO-16DE-10',
     38: 'AT-MIO-64E-3',
     39: 'AT-MIO-16XE-50',
     40: 'NEC-AI-16E-4',
     41: 'NEC-MIO-16XE-50',
     42: 'NEC-AI-16XE-50',
     44: 'AT-MIO-16E-1',
     50: 'AT-MIO-16XE-10',
     51: 'AT-AI-16XE-10',
     52: 'DAQCard-AI-16XE-50',
     53: 'DAQCard-AI-16E-4',
     65: 'PC-DIO-24/PnP',
     66: 'PC-DIO-96/PnP',
     67: 'AT-DIO-32HS',
     68: 'DAQCard-6533',
     75: 'DAQPad-6507',
     75: 'DAQPad-6508',
     76: 'DAQPad-6020E for USB',
     88: 'DAQCard-6062E',
     89: 'DAQCard-6715',
     90: 'DAQCard-6023E',
     91: 'DAQCard-6024E',
    200: 'PCI-DIO-96',
    201: 'PCI-',
    202: 'PCI-MIO-16XE-50',
    203: 'PCI-5102',
    204: 'PCI-MIO-16XE-10',
    205: 'PCI-MIO-16E-1',
    206: 'PCI-MIO-16E-4',
    207: 'PXI-6070E',
    208: 'PXI-6040E',
    209: 'PXI-6030E',
    210: 'PXI-6011E',
    211: 'PCI-DIO-32HS',
    215: 'PXI-6533',
    216: 'PCI-6534',
    218: 'PXI-6534',
    220: 'PCI-6031E (MIO-64XE-10)',
    221: 'PCI-6032E (AI-16XE-10)',
    222: 'PCI-6033E (AI-64XE-10)',
    223: 'PCI-6071E (MIO-64E-1)',
    232: 'PCI-6602',
    233: 'NI 4451 for PCI',
    234: 'NI 4452 for PCI',
    235: 'NI 4551 for PCI',
    236: 'NI 4552 for PCI',
    237: 'PXI-6602',
    240: 'PXI-6508',
    241: 'PCI-6110',
    244: 'PCI-6111',
    256: 'PCI-6503',
    257: 'PXI-6503',
    258: 'PXI-6071E',
    259: 'PXI-6031E',
    261: 'PCI-6711',
    262: 'PCI-6711',
    263: 'PCI-6713',
    264: 'PXI-6713',
    265: 'PCI-6704',
    266: 'PXI-6704',
    267: 'PCI-6023E',
    268: 'PXI-6023E',
    269: 'PCI-6024E',
    270: 'PXI-6024E',
    271: 'PCI-6025E',
    272: 'PXI-6025E',
    273: 'PCI-6052E',
    274: 'PXI-6052E',
    275: 'DAQPad-6070E (for 1394)',
    276: 'DAQPad-6052E for 1394 (mass termination)',
    285: 'PCI-6527',
    286: 'PXI-6527',
    308: 'PCI-6601',
    311: 'PCI-6703',
    314: 'PCI-6034E',
    315: 'PXI-6034E',
    316: 'PCI-6035E',
    317: 'PXI-6035E',
    318: 'PXI-6703',
    319: 'PXI-6608',
    321: 'NI 4454 for PCI',
    327: 'PCI-6608',
    329: 'NI 6222 for PCI',
    330: 'NI 6222 for PXI',
    331: 'NI 6224 for Ethernet',
    332: 'DAQPad-6052E for USB',
    335: 'NI 4472 for PXI/CompactPCI',
    338: 'PCI-6115',
    339: 'PXI-6115',
    340: 'PCI-6120',
    341: 'PXI-6120',
    342: 'NI 4472 for PCI',
    348: 'DAQCard-6036E',
    348: 'NI 6036E for PCI',
    349: 'NI 6731 for PCI',
    350: 'NI 6733 for PCI',
    351: 'NI 6731 for PXI/Compact PCI',
    352: 'NI 6733 for PXI/Compact PCI',
    353: 'PCI-4474',
    354: 'PXI-4474',
    361: 'DAQPad-6052E for 1394 (BNC)',
    366: 'PCI-6013',
    367: 'PCI-6014'}

ErrorCodes = {
    -10001: ('syntaxError', 'An Error was detected in the input string; the arrangement or ordering of the characters in the string is not consistent with the expected ordering'),
    -10002: ('semanticsError', 'An Error', 'was detected in the input string; the syntax of the string is correct, but certain values specified in the string are inconsistent with other values specified in the string'),
    -10003: ('invalidValueError', 'The value of a numeric parameter is invalid'),
    -10004: ('valueConflictError', 'The value of a numeric parameter is inconsistent with another one, and therefore the combination is invalid'),
    -10005: ('badDeviceError', 'The device is invalid'),
    -10006: ('badLineError', 'The line is invalid'),
    -10007: ('badChanError', 'A channel, port, or counter is out of range for the device type or device configuration; or the combination of channels is not allowed; or the scan order must be reversed (0 last)'),
    -10008: ('badGroupError', 'The group is invalid'),
    -10009: ('badCounterError', 'The counter is invalid'),
    -10010: ('badCountError', 'The count is too small or too large for the specified counter, or the given I/O transfer count is not appropriate for the current buffer or channel configuration'),
    -10011: ('badIntervalError', 'The analog input scan rate is too fast for the number of channels and the channel clock rate; or the given clock rate is not supported by the associated counter channel or I/O channel'),
    -10012: ('badRangeError', 'The analog input or analog output voltage or current range is invalid for the specified channel, or you are writing an invalid voltage or current to the analog output'),
    -10013: ('badErrorCodeError', 'The driver returned an unrecognized or unlisted Error', 'code'),
    -10014: ('groupTooLargeError', 'The group size is too large for the device'),
    -10015: ('badTimeLimitError', 'The time limit is invalid'),
    -10016: ('badReadCountError', 'The read count is invalid'),
    -10017: ('badReadModeError', 'The read mode is invalid'),
    -10018: ('badReadOffsetError', 'The offset is unreachable'),
    -10019: ('badClkFrequencyError', 'The frequency is invalid'),
    -10020: ('badTimebaseError', 'The timebase is invalid'),
    -10021: ('badLimitsError', 'The limits are beyond the range of the device'),
    -10022: ('badWriteCountError', 'Your data array contains an incomplete update, or you are trying to write past the end of the internal buffer, or your output operation is continuous and the length of your array is not a multiple of one half of the internal buffer size'),
    -10023: ('badWriteModeError', 'The write mode is out of range or is disallowed'),
    -10024: ('badWriteOffsetError', 'Adding the write offset to the write mark places the write mark outside the internal buffer'),
    -10025: ('limitsOutOfRangeError', "The requested input limits exceed the device's capability or configuration. Alternative limits were selected"),
    -10026: ('badBufferSpecificationError', 'The requested number of buffers or the buffer size is not allowed. For example, the buffer limit for Lab and devices is 64K samples, or the device does not support multiple buffers'),
    -10027: ('badDAQEventError', 'For DAQEvents 0 and 1 general value A must be greater than 0 and less than the internal buffer size. If DMA is used for DAQEvent 1, general value A must divide the internal buffer size evenly, with no remainder. If the TIO-10 is used for DAQEvent 4, general value A must be 1 or 2.'),
    -10028: ('badFilterCutoffError', 'The cutoff frequency specified is not valid for this device'),
    -10029: ('obsoleteFunctionError', 'The function you are calling is no longer supported in this version of the driver'),
    -10030: ('badBaudRateError', 'The specified baud rate for communicating with the serial port is not valid on this platform'),
    -10031: ('badChassisIDError', 'The specified SCXI chassis does not correspond to a configured SCXI chassis'),
    -10032: ('badModuleSlotError', 'The SCXI module slot that was specified is invalid or corresponds to an empty slot'),
    -10033: ('invalidWinHandleError', 'The window handle passed to the function is invalid'),
    -10034: ('noSuchMessageError', 'No configured message matches the one you tried to delete'),
    -10035: ('irrelevantAttributeError', 'The specified attribute is not relevant'),
    -10036: ('badYearError', 'The specified year is invalid'),
    -10037: ('badMonthError', 'The specified month is invalid'),
    -10038: ('badDayError', 'The specified day is invalid'),
    -10039: ('stringTooLongError', 'The specified input string is too long. For instance, DAQScope 5102 devices can only store a string up to 32 bytes in length on the calibration EEPROM. In that case, please shorten the string'),
    -10040: ('badGroupSizeError', 'The group size is invalid'),
    -10041: ('badTaskIDError', 'The specified task ID is invalid. For instance, you may have connected a taskID from an Analog Input VI to a Digital I/O VI'),
    -10042: ('inappropriateControlCodeError', 'The specified control code is inappropriate for the current configuration or state'),
    -10043: ('badDivisorError', 'The specified divisor is invalid'),
    -10044: ('badPolarityError', 'The specified polarity is invalid'),
    -10045: ('badInputModeError', 'The specified input mode is invalid'),
    -10046: ('badExcitationError', 'The excitation value specified is not valid for this device'),
    -10047: ('badConnectionTypeError', 'The type of SCXI channel connection specified is not valid for this module'),
    -10048: ('badExcitationTypeError', 'The excitation type specified is not valid for this device'),
    -10050: ('badChanListError', 'There is more than one channel name in the channel list that corresponds to the same hardware channel'),
    -10079: ('badTrigSkipCountError', 'The trigger skip count is invalid'),
    -10080: ('badGainError', 'The gain or gain adjust is invalid'),
    -10081: ('badPretrigCountError', 'The pretrigger sample count is invalid'),
    -10082: ('badPosttrigCountError', 'The posttrigger sample count is invalid'),
    -10083: ('badTrigModeError', 'The trigger mode is invalid'),
    -10084: ('badTrigCountError', 'The trigger count is invalid'),
    -10085: ('badTrigRangeError', 'The trigger range or trigger hysteresis window is invalid'),
    -10086: ('badExtRefError', 'The external reference is invalid'),
    -10087: ('badTrigTypeError', 'The trigger type is invalid'),
    -10088: ('badTrigLevelError', 'The trigger level is invalid'),
    -10089: ('badTotalCountError', 'The total count is inconsistent with the buffer size and pretrigger scan count or with the device type'),
    -10090: ('badRPGError', 'The individual range, polarity, and gain settings are valid but the combination is not allowed'),
    -10091: ('badIterationsError', 'You have attempted to use an invalid setting for the iterations parameter. The iterations value must be 0 or greater. Your device might be limited to only two values, 0 and 1'),
    -10092: ('lowScanIntervalError', 'Some devices require a time gap between the last sample in a scan and the start of the next scan. The scan interval you have specified does not provide a large enough gap for the device. See your documentation for an explanation'),
    -10093: ('fifoModeError', 'FIFO mode waveform generation cannot be used because at least one condition is not satisfied'),
    -10094: ('badCalDACconstError', 'The calDAC constant passed to the function is invalid'),
    -10095: ('badCalStimulusError', 'The calibration stimulus passed to the function is invalid'),
    -10096: ('badCalibrationConstantError', 'The specified calibration constant is invalid'),
    -10097: ('badCalOpError', 'The specified calibration operation is invalid'),
    -10098: ('badCalConstAreaError', 'The specified calibration constant area is invalid. For instance, the specified calibration constant area contains constants which cannot be modified outside the factory'),
    -10100: ('badPortWidthError', 'The requested digital port width is not a multiple of the hardware port width or is not attainable by the DAQ hardware'),
    -10120: ('gpctrBadApplicationError', 'Invalid application used'),
    -10121: ('gpctrBadCtrNumberError', 'Invalid counterNumber used'),
    -10122: ('gpctrBadParamValueError', 'Invalid paramValue used'),
    -10123: ('gpctrBadParamIDError', 'Invalid paramID used'),
    -10124: ('gpctrBadEntityIDError', 'Invalid entityID used'),
    -10125: ('gpctrBadActionError', 'Invalid action used'),
    -10126: ('gpctrSourceSelectError', 'Invalid source selected'),
    -10127: ('badCountDirError', 'The specified counter does not support the specified count direction'),
    -10128: ('badGateOptionError', 'The specified gating option is invalid'),
    -10129: ('badGateModeError', 'The specified gate mode is invalid'),
    -10130: ('badGateSourceError', 'The specified gate source is invalid'),
    -10131: ('badGateSignalError', 'The specified gate signal is invalid'),
    -10132: ('badSourceEdgeError', 'The specified source edge is invalid'),
    -10133: ('badOutputTypeError', 'The specified output type is invalid'),
    -10134: ('badOutputPolarityError', 'The specified output polarity is invalid'),
    -10135: ('badPulseModeError', 'The specified pulse mode is invalid'),
    -10136: ('badDutyCycleError', 'The specified duty cycle is invalid'),
    -10137: ('badPulsePeriodError', 'The specified pulse period is invalid'),
    -10138: ('badPulseDelayError', 'The specified pulse delay is invalid'),
    -10139: ('badPulseWidthError', 'The specified pulse width is invalid'),
    -10140: ('badFOUTportError', 'The specified frequency output (FOUT or FREQ_OUT) port is invalid'),
    -10141: ('badAutoIncrementModeError', 'The specified autoincrement mode is invalid'),
    -10150: ('CfgInvalidatedSysCalError', 'Hardware configuration has changed since last system calibration'),
    -10151: ('sysCalOutofDateError', 'system calibration is out of date'),
    -10180: ('badNotchFilterError', 'The specified notch filter is invalid'),
    -10181: ('badMeasModeError', 'The specified measurement mode is invalid'),
    -10200: ('EEPROMreadError', 'Unable to read data from EEPROM'),
    -10201: ('EEPROMwriteError', 'Unable to write data to EEPROM'),
    -10202: ('EEPROMwriteProtectionError', 'You cannot write into this location or area of your EEPROM because it is write–protected. You may be trying to store calibration constants into a write–protected area; if this is the case, you should select user area of the EEPROM instead'),
    -10203: ('EEPROMinvalidLocationError', 'The specified EEPROM location is invalid'),
    -10204: ('EEPROMinvalidPasswordError', 'The password for accessing the EEPROM is incorrect'),
    -10240: ('noDriverError', 'The driver interface could not locate or open the driver'),
    -10241: ('oldDriverError', 'One of the driver files or the configuration utility is out of date, or a particular feature of the Channel Wizard is not supported in this version of the driver'),
    -10242: ('functionNotFoundError', 'The specified function is not located in the driver'),
    -10243: ('configFileError', 'The driver could not locate or open the configuration file, or the format of the configuration file is not compatible with the currently installed driver'),
    -10244: ('deviceInitError', 'The driver encountered a hardware-initialization Error', 'while attempting to configure the specified device'),
    -10245: ('osInitError', 'The driver encountered an operating-system Error', 'while attempting to perform an operation, or the operating system does not support an operation performed by the driver'),
    -10246: ('communicationsError', 'The driver is unable to communicate with the specified external device'),
    -10247: ('cmosConfigError', 'The CMOS configuration-memory for the device is empty or invalid, or the configuration specified does not agree with the current configuration of the device, or the EISA system configuration is invalid'),
    -10248: ('dupAddressError', 'The base addresses for two or more devices are the same; consequently, the driver is unable to access the specified device'),
    -10249: ('intConfigError', 'The interrupt configuration is incorrect given the capabilities of the computer or device'),
    -10250: ('dupIntError', 'The interrupt levels for two or more devices are the same'),
    -10251: ('dmaConfigError', 'The DMA configuration is incorrect given the capabilities of the computer/DMA controller or device'),
    -10252: ('dupDMAError', 'The DMA channels for two or more devices are the same'),
    -10253: ('jumperlessBoardError', 'Unable to find one or more jumperless devices you have configured using the Measurement & Automation Explorer'),
    -10254: ('DAQCardConfError', 'Cannot configure the DAQCard because 1) the correct version of the card and socket services software is not installed; 2) the card in the PCMCIA socket is not a DAQCard; or 3) the base address and/or interrupt level requested are not available according to the card and socket services resource manager. Try different settings or use AutoAssign in the Measurement & Automation Explorer'),
    -10256: ('comPortOpenError', 'There was an Error', 'in opening the specified COM port'),
    -10257: ('baseAddressError', 'Bad base address specified in Measurement & Automation Explorer'),
    -10258: ('dmaChannel1Error', 'Bad DMA channel 1 specified in Measurement & Automation Explorer or by the operating system'),
    -10259: ('dmaChannel2Error', 'Bad DMA channel 2 specified in Measurement & Automation Explorer or by the operating system'),
    -10260: ('dmaChannel3Error', 'Bad DMA channel 3 specified in Measurement & Automation Explorer or by the operating system'),
    -10261: ('userModeToKernelModeCallError', 'The user mode code failed when calling the kernel mode code'),
    -10340: ('noConnectError', 'No RTSI or PFI signal/line is connected, or the specified signal and the specified line are not connected, or your connection to an RDA server either cannot be made or has been terminated'),
    -10341: ('badConnectError', 'The RTSI or PFI signal/line cannot be connected as specified'),
    -10342: ('multConnectError', 'The specified RTSI signal is already being driven by a RTSI line, or the specified RTSI line is already being driven by a RTSI signal'),
    -10343: ('SCXIConfigError', 'The specified SCXI configuration parameters are invalid, or the function cannot be executed with the current SCXI configuration'),
    -10347: ('chassisCommunicationError', 'There was an Error', 'in sending a packet to the remote chassis. Check your serial port cable connections'),
    -10349: ('SCXIModuleTypeConflictError', 'The module ID read from the SCXI module conflicts with the configured module type'),
    -10350: ('CannotDetermineEntryModuleError', 'Neither an SCXI entry module (i.e.: the SCXI module cabled to the measurement device that performs the acquisition/control operation) has been specified by the user, nor can Traditional NI-DAQ (Legacy) uniquely determine the entry module for the current SCXI configuration'),
    -10360: ('DSPInitError', 'The DSP driver was unable to load the kernel for its operating system'),
    -10370: ('badScanListError', 'The scan list is invalid; for example, you are mixing AMUX-64T channels and onboard channels, scanning SCXI channels out of order, or have specified a different starting channel for the same SCXI module. Also, the driver attempts to achieve complicated gain distributions over SCXI channels on the same module by manipulating the scan list and returns this Error', 'if it fails'),
    -10380: ('invalidSignalSrcError', 'The specified signal source is invalid for the selected signal name'),
    -10381: ('invalidSignalNameError', 'The specified signal name is invalid'),
    -10382: ('invalidSrcSpecError', 'The specified source specification is invalid for the signal source or signal name'),
    -10383: ('invalidSignalDestError', 'The specified signal destination is invalid'),
    -10390: ('routingError', 'The routing manager was unable to complete the request due to a lack of resources, or because the required resources are reserved'),
    -10391: ('pfiBadLineError', 'The routing manager was unable to complete the request due to an invalid PFI line number'),
    -10392: ('pfiGPCTRNotRoutedError', 'The specified General Purpose Counter Output and/or Up/Down signal(s) are not routed to any PFI lines'),
    -10393: ('pfiDefaultLineUndefinedError', 'A default PFI line does not exist for the given signal. You must specify the PFI line either explicitly in the VI, or through the PFI line configuration VI'),
    -10394: ('pfiDoubleRoutingError', 'Given PFI line is already reserved for a different signal, or given signal has already reserved a different PFI line'),
    -10400: ('userOwnedRsrcError', 'The specified resource is owned by the user and cannot be accessed or modified by the driver'),
    -10401: ('unknownDeviceError', 'The specified device is not a National Instruments product, the driver does not support the device (for example, the driver was released before the device was supported), or the device has not been configured using the Measurement & Automation Explorer'),
    -10402: ('deviceNotFoundError', 'No device is located in the specified slot or at the specified address'),
    -10403: ('deviceSupportError', 'The specified device does not support the requested action (the driver recognizes the device, but the action is inappropriate for the device)'),
    -10404: ('noLineAvailError', 'No line is available'),
    -10405: ('noChanAvailError', 'No channel is available'),
    -10406: ('noGroupAvailError', 'No group is available'),
    -10407: ('lineBusyError', 'The specified line is in use'),
    -10408: ('chanBusyError', 'The specified channel is in use'),
    -10409: ('groupBusyError', 'The specified group is in use'),
    -10410: ('relatedLCGBusyError', 'A related line, channel, or group is in use; if the driver configures the specified line, channel, or group, the configuration, data, or handshaking lines for the related line, channel, or group will be disturbed'),
    -10411: ('counterBusyError', 'The specified counter is in use'),
    -10412: ('noGroupAssignError', 'No group is assigned, or the specified line or channel cannot be assigned to a group'),
    -10413: ('groupAssignError', 'A group is already assigned, or the specified line or channel is already assigned to a group'),
    -10414: ('reservedPinError', 'The selected signal requires a pin that is reserved and configured only by Traditional NI-DAQ (Legacy). You cannot configure this pin yourself'),
    -10415: ('externalMuxSupportError', 'This function does not support your DAQ device when an external multiplexer (such as an AMUX–64T or SCXI) is connected to it'),
    -10440: ('sysOwnedRsrcError', 'The specified resource is owned by the driver and cannot be accessed or modified by the user'),
    -10441: ('memConfigError', 'No memory is configured to support the current data-transfer mode, or the configured memory does not support the current data-transfer mode. (If block transfers are in use, the memory must be capable of performing block transfers'),
    -10442: ('memDisabledError', 'The specified memory is disabled or is unavailable given the current addressing mode'),
    -10443: ('memAlignmentError', 'The transfer buffer is not aligned properly for the current data-transfer mode. For example, the buffer is at an odd address, is not aligned to a 32-bit boundary, is not aligned to a 512-bit boundary, and so on. Alternatively, the driver is unable to align the buffer because the buffer is too small. For DSA devices, buffer should be an array of i32. These devices return the data in a 32-bit format in which the data bits are in the most significant bits. The buffer must be aligned on a 4-byte boundary. If the buffer is allocated as an array of i32s, it must be typecast to an i16 pointer when passing its address to DAQ_Op. If the buffer is allocated as a double-sized array of i16s, the user must check that the buffer is aligned on a 4-byte boundary before passing the buffer to DAQ_Op'),
    -10444: ('memFullError', 'No more system memory is available on the heap, or no more memory is available on the device, or insufficient disk space is available'),
    -10445: ('memLockError', 'The transfer buffer cannot be locked into physical memory. On PC AT machines, portions of the DMA data acquisition buffer may be in an invalid DMA region, for example, above 16 megabytes'),
    -10446: ('memPageError', 'The transfer buffer contains a page break; system resources may require reprogramming when the page break is encountered'),
    -10447: ('memPageLockError', 'The operating environment is unable to grant a page lock'),
    -10448: ('stackMemError', 'The driver is unable to continue parsing a string input due to stack limitations'),
    -10449: ('cacheMemError', 'A cache-related Error', 'occurred, or caching is not supported in the current mode'),
    -10450: ('physicalMemError', 'A hardware Error', 'occurred in physical memory, or no memory is located at the specified address'),
    -10451: ('virtualMemError', 'The driver is unable to make the transfer buffer contiguous in virtual memory and therefore cannot lock it into physical memory; thus, the buffer cannot be used for DMA transfers'),
    -10452: ('noIntAvailError', 'No interrupt level is available for use'),
    -10453: ('intInUseError', 'The specified interrupt level is already in use by another device'),
    -10454: ('noDMACError', 'No DMA controller is available in the system'),
    -10455: ('noDMAAvailError', 'No DMA channel is available for use'),
    -10456: ('DMAInUseError', 'The specified DMA channel is already in use by another device'),
    -10457: ('badDMAGroupError', 'DMA cannot be configured for the specified group because it is too small, too large, or misaligned. Consult the device documentation to determine group ramifications with respect to DMA'),
    -10458: ('diskFullError', 'The storage disk you specified is full'),
    -10459: ('DLLInterfaceError', 'The Traditional NI-DAQ (Legacy) DLL could not be called due to an interface error'),
    -10460: ('interfaceInteractionError', 'You have mixed VIs from the DAQ library and the _DAQ compatibility library (LabVIEW 2.2 style VIs). You may switch between the two libraries only by running the DAQ VI Device Reset before calling _DAQ compatibility VIs or by running the compatibility VI Board Reset before calling DAQ VIs'),
    -10461: ('resourceReservedError', 'The specified resource is unavailable because it has already been reserved by another entity'),
    -10462: ('resourceNotReservedError', 'The specified resource has not been reserved, so the action is not allowed'),
    -10463: ('mdResourceAlreadyReservedError', 'Another entity has already reserved the requested resource'),
    -10464: ('mdResourceReservedError', 'Attempted to access a reserved resource that requires the usage of a key'),
    -10465: ('mdResourceNotReservedError', 'Attempting to lift a reservation off a resource that previously had no reservation'),
    -10466: ('mdResourceAccessKeyError', 'The requested operation cannot be performed because the key supplied is invalid'),
    -10467: ('mdResourceNotRegisteredError', 'The resource requested is not registered with the minidriver'),
    -10480: ('muxMemFullError', 'The scan list is too large to fit into the mux-gain memory of the device'),
    -10481: ('bufferNotInterleavedError', 'You must provide a single buffer of interleaved data, and the channels must be in ascending order. You cannot use DMA to transfer data from two buffers; however, you may be able to use interrupts'),
    -10482: ('waveformBufferSizeError', 'You have specified channels with different waveform lengths. To fix the problem, ensure that the waveform data for every channel has the same number of array elements'),
    -10540: ('SCXIModuleNotSupportedError', 'At least one of the SCXI modules specified is not supported for the operation'),
    -10541: ('TRIG1ResourceConflict CTRB1 will drive COUTB1, however CTRB1 will also drive TRIG1. This may cause unpredictable results when scanning the chassis'),
    -10542: ('matrixTerminalBlockError', 'This function requires that no Matrix terminal block is configured with the SCXI module'),
    -10543: ('noMatrixTerminalBlockError', 'This function requires that some matrix terminal block is configured with the SCXI module'),
    -10544: ('invalidMatrixTerminalBlockError', 'The type of matrix terminal block configured will not allow proper operation of this function with the given parameters'),
    -10560: ('invalidDSPHandleError', 'The DSP handle input is not valid'),
    -10561: ('DSPDataPathBusyError', 'Either DAQ or WFM can use a PC memory buffer, but not both at the same time'),
    -10600: ('noSetupError', 'No setup operation has been performed for the specified resources. Or, some resources require a specific ordering of calls for proper setup'),
    -10601: ('multSetupError', 'The specified resources have already been configured by a setup operation'),
    -10602: ('noWriteError', 'No output data has been written into the transfer buffer'),
    -10603: ('groupWriteError', 'The output data associated with a group must be for a single channel or must be for consecutive channels'),
    -10604: ('activeWriteError', 'Once data generation has started, only the transfer buffers originally written to may be updated. If DMA is active and a single transfer buffer contains interleaved channel-data, new data must be provided for all output channels currently using the DMA channel'),
    -10605: ('endWriteError', 'No data was written to the transfer buffer because the final data block has already been loaded'),
    -10606: ('notArmedError', 'The specified resource is not armed'),
    -10607: ('armedError', 'The specified resource is already armed'),
    -10608: ('noTransferInProgError', 'No transfer is in progress for the specified resource'),
    -10609: ('transferInProgError', 'A transfer is already in progress for the specified resource, or the operation is not allowed because the device is in the process of performing transfers, possibly with different resources'),
    -10610: ('transferPauseError', 'A single output channel in a group may not be paused if the output data for the group is interleaved'),
    -10611: ('badDirOnSomeLinesError', 'Some of the lines in the specified channel are not configured for the transfer direction specified. For a write transfer, some lines are configured for input. For a read transfer, some lines are configured for output'),
    -10612: ('badLineDirError', 'The specified line does not support the specified transfer direction'),
    -10613: ('badChanDirError', 'The specified channel does not support the specified transfer direction, or you have performed an operation on a digital port or line configured for the opposite direction'),
    -10614: ('badGroupDirError', 'The specified group does not support the specified transfer direction'),
    -10615: ('masterClkError', 'The clock configuration for the clock master is invalid'),
    -10616: ('slaveClkError', 'The clock configuration for the clock slave is invalid'),
    -10617: ('noClkSrcError', 'No source signal has been assigned to the clock resource'),
    -10618: ('badClkSrcError', 'The specified source signal cannot be assigned to the clock resource'),
    -10619: ('multClkSrcError', 'A source signal has already been assigned to the clock resource'),
    -10620: ('noTrigError', 'No trigger signal has been assigned to the trigger resource'),
    -10621: ('badTrigError', 'The specified trigger signal cannot be assigned to the trigger resource'),
    -10622: ('preTrigError', 'The pretrigger mode is not supported or is not available in the current configuration, or no pretrigger source has been assigned'),
    -10623: ('postTrigError', 'No posttrigger source has been assigned'),
    -10624: ('delayTrigError', 'The delayed trigger mode is not supported or is not available in the current configuration, or no delay source has been assigned'),
    -10625: ('masterTrigError', 'The trigger configuration for the trigger master is invalid'),
    -10626: ('slaveTrigError', 'The trigger configuration for the trigger slave is invalid'),
    -10627: ('noTrigDrvError', 'No signal has been assigned to the trigger resource'),
    -10628: ('multTrigDrvError', 'A signal has already been assigned to the trigger resource'),
    -10629: ('invalidOpModeError', 'The specified operating mode is invalid, or the resources have not been configured for the specified operating mode'),
    -10630: ('invalidReadError', 'The parameters specified to read data were invalid in the context of the acquisition. For example, an attempt was made to read 0 bytes from the transfer buffer, or an attempt was made to read past the end of the transfer buffer'),
    -10631: ('noInfiniteModeError', 'Continuous input or output transfers are not allowed in the current operating mode, or continuous operation is not allowed for this type of device'),
    -10632: ('someInputsIgnoredError', 'Certain inputs were ignored because they are not relevant in the current operating mode'),
    -10633: ('invalidRegenModeError', 'The specified analog output regeneration mode is not allowed for this device'),
    -10634: ('noContTransferInProgressError', 'No continuous (double buffered) transfer is in progress for the specified resource'),
    -10635: ('invalidSCXIOpModeError', 'Either the SCXI operating mode specified in a configuration call is invalid, or a module is in the wrong operating mode to execute the function call'),
    -10636: ('noContWithSynchError', 'You cannot start a continuous (double-buffered) operation with a synchronous function call'),
    -10637: ('bufferAlreadyConfigError', 'Attempted to configure a buffer after the buffer had already been configured. You can configure a buffer only once'),
    -10638: ('badClkDestError', 'The clock cannot be assigned to the specified destination'),
    -10670: ('rangeBadForMeasModeError', 'The input range is invalid for the configured measurement mode'),
    -10671: ('autozeroModeConflictError', 'Autozero cannot be enabled for the configured measurement mode'),
    -10680: ('badChanGainError', 'All channels of this device must have the same gain'),
    -10681: ('badChanRangeError', 'All channels of this device must have the same range'),
    -10682: ('badChanPolarityError', 'All channels of this device must be the same polarity'),
    -10683: ('badChanCouplingError', 'All channels of this device must have the same coupling'),
    -10684: ('badChanInputModeError', 'All channels of this device must have the same input mode'),
    -10685: ('clkExceedsBrdsMaxConvRateError', "The clock rate exceeds the device's recommended maximum rate"),
    -10686: ('scanListInvalidError', 'A configuration change has invalidated the scan list'),
    -10687: ('bufferInvalidError', 'A configuration change has invalidated the acquisition buffer, or an acquisition buffer has not been configured'),
    -10688: ('noTrigEnabledError', 'The number of total scans and pretrigger scans implies that a triggered start is intended, but triggering is not enabled'),
    -10689: ('digitalTrigBError', 'Digital trigger B is illegal for the number of total scans and pretrigger scans specified'),
    -10690: ('digitalTrigAandBError', 'This device does not allow digital triggers A and B to be enabled at the same time'),
    -10691: ('extConvRestrictionError', 'This device does not allow an external sample clock with an external scan clock, start trigger, or stop trigger'),
    -10692: ('chanClockDisabledError', 'The acquisition cannot be started because the channel clock is disabled'),
    -10693: ('extScanClockError', 'You cannot use an external scan clock when doing a single scan of a single channel'),
    -10694: ('unsafeSamplingFreqError', 'The scan rate is above the maximum or below the minimum for the hardware, gains, and filters used'),
    -10695: ('DMAnotAllowedError', 'You have set up an operation that requires the use of interrupts. DMA is not allowed. For example, some DAQ events, such as messaging and LabVIEW occurrences, require interrupts'),
    -10696: ('multiRateModeError', 'Multi-rate scanning cannot be used with the AMUX-64, SCXI, or pretriggered acquisitions'),
    -10697: ('rateNotSupportedError', 'Unable to convert your timebase/interval pair to match the actual hardware capabilities of this device'),
    -10698: ('timebaseConflictError', 'You cannot use this combination of scan and sample clock timebases for this device'),
    -10699: ('polarityConflictError', 'You cannot use this combination of scan and sample clock source polarities for this operation and device'),
    -10700: ('signalConflictError', 'You cannot use this combination of scan and convert clock signal sources for this operation and device'),
    -10701: ('noLaterUpdateError', 'The call had no effect because the specified channel had not been set for later internal update'),
    -10710: ('noHandshakeModeError', 'The specified port has not been configured for handshaking'),
    -10720: ('noEventCtrError', 'The specified counter is not configured for event-counting operation'),
    -10740: ('SCXITrackHoldError', 'A signal has already been assigned to the SCXI track-and-hold trigger line, or a control call was inappropriate because the specified module is not configured for one-channel operation'),
    -10780: ('sc2040InputModeError', 'When you have an SC2040 attached to your device, all analog input channels must be configured for differential input mode'),
    -10781: ('outputTypeMustBeVoltageError', 'The polarity of the output channel cannot be bipolar when outputting currents'),
    -10782: ('sc2040HoldModeError', 'The specified operation cannot be performed with the SC-2040: (configured in hold mode'),
    -10783: ('calConstPolarityConflictError', 'Calibration constants in the load area have a different polarity from the current configuration. Therefore, you should load constants from factory'),
    -10784: ('masterDeviceNotInPXISlot2 Your master device must be PXI slot number 2 in order to route clocks to slave devices. PXI slot 2 is the STAR trigger controller slot. Only modules in slot 2 can drive the STAR trigger lines'),
    -10800: ('timeOutError', 'The operation could not complete within the time limit'),
    -10801: ('calibrationError', 'An Error', 'occurred during the calibration process. Possible reasons for this Error', 'include incorrect connection of the stimulus signal, incorrect value of the stimulus signal, or malfunction of your DAQ device'),
    -10802: ('dataNotAvailError', 'The requested amount of data has not yet been acquired'),
    -10803: ('transferStoppedError', 'The on-going transfer has been stopped. This is to prevent regeneration for output operations, or to reallocate resources for input operations'),
    -10804: ('earlyStopError', 'The transfer stopped prior to reaching the end of the transfer buffer'),
    -10805: ('overRunError', 'The clock rate is faster than the hardware can support. An attempt to input or output a new data point was made before the hardware could finish processing the previous data point. This condition may also occur when glitches are present on an external clock signal'),
    -10806: ('noTrigFoundError', 'No trigger value was found in the input transfer buffer'),
    -10807: ('earlyTrigError', 'The trigger occurred before sufficient pretrigger data was acquired'),
    -10808: ('LPTcommunicationError', 'An Error', 'occurred in the parallel port communication with the DAQ device'),
    -10809: ('gateSignalError', 'Attempted to start a pulse width measurement with the pulse in the phase to be measured (e.g., high phase for high-level gating)'),
    -10810: ('internalDriverError', 'An unexpected Error', 'occurred inside the driver when performing this given operation'),
    -10811: ('frequencyMeasurementError', "The input signal's frequency could not be measured. The input signal's frequency may be outside the expected frequency range, or the threshhold and hysteresis values may not be being crossed"),
    -10840: ('softwareError', 'The contents or the location of the driver file was changed between accesses to the driver'),
    -10841: ('firmwareError', 'The firmware does not support the specified operation, or the firmware operation could not complete due to a data-integrity problem'),
    -10842: ('hardwareError', 'The hardware is not responding to the specified operation, or the response from the hardware is not consistent with the functionality of the hardware'),
    -10843: ('underFlowError', 'Because of system and/or bus-bandwidth limitations, the driver could not write data to the device fast enough to keep up with the device throughput; the onboard device memory reported an underflow error. This Error', 'may be returned erroneously when an overrun Error', 'has occurred'),
    -10844: ('underWriteError', 'Your application was unable to deliver data to the background generation buffer fast enough so new data could not be delivered to the device. To prevent this error, you might increase the size of the background generation buffer, increase the amount of data you write to it per call to the write function/VI, slow down your generation rate, or reduce the number of tasks your computer is performing'),
    -10845: ('overFlowError', 'Because of system and/or bus-bandwidth limitations, the driver could not read data from the device fast enough to keep up with the device throughput; the onboard device memory reported an overflow error'),
    -10846: ('overWriteError', 'Your application was unable to retrieve data from the background acquisition buffer fast enough so the unretrieved data was overwritten with new data. To prevent this error, you might increase the size of the background acquisition buffer, increase the amount of data you read from it per call to the read function/VI, slow down your acquisition rate, or reduce the number of tasks your computer is performing'),
    -10847: ('dmaChainingError', 'New buffer information was not available at the time of the DMA chaining interrupt; DMA transfers will terminate at the end of the currently active transfer buffer'),
    -10848: ('noDMACountAvailError', 'The driver could not obtain a valid reading from the transfer-count register in the DMA controller'),
    -10849: ('OpenFileError', 'The configuration file or DSP kernel file could not be opened'),
    -10850: ('closeFileError', 'Unable to close a file'),
    -10851: ('fileSeekError', 'Unable to seek within a file'),
    -10852: ('readFileError', 'Unable to read from a file'),
    -10853: ('writeFileError', 'Unable to write to a file'),
    -10854: ('miscFileError', 'An Error', 'occurred accessing a file'),
    -10855: ('osUnsupportedError', 'Traditional NI-DAQ (Legacy) does not support the current operation on this particular version of the operating system'),
    -10856: ('osError', 'An unexpected Error', 'occurred from the operating system while performing the given operation'),
    -10857: ('internalKernelError', 'An unexpected Error', 'occurred inside the kernel of the device while performing this operation'),
    -10858: ('hardwareConfigChangedError', 'The system has reconfigured the device and has invalidated the existing configuration. The device requires reinitialization to be used again'),
    -10880: ('updateRateChangeError', 'A change to the update rate is not possible at this time because 1) when waveform generation is in progress, you cannot change the interval timebase or 2) when you make several changes in a row, you must give each change enough time to take effect before requesting further changes'),
    -10881: ('partialTransferCompleteError', 'You cannot do another transfer after a successful partial transfer'),
    -10884: ('pretrigReorderError', 'Could not rearrange data after a pretrigger acquisition completed'),
    -10885: ('overLoadError', 'The input signal exceeded the input range of the ADC'),
    -10920: ('gpctrDataLossError', 'One or more data points may have been lost during buffered GPCTR operations due to speed limitations of your system') }

if __name__ == '__main__':
    print ErrorCodes[-10884]
